[package]
name = "floppy-driver-rs"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[features]
testing = []

[dependencies]
teensycore = { version = "0.1.0" }
