[package]
name = "random-access-floppy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[features]
testing = []

[dependencies]
teensycore = { path = "../teensycore" }