pub static INDEX_PIN: usize = 3; // This pin assigmnet is recrational. DO NOT CHANGE. It won't work.
pub static DRIVE_PIN: usize = 4;
pub static MOTOR_PIN: usize = 5;
pub static DIR_PIN: usize = 6;
pub static STEP_PIN: usize = 7;
pub static WRITE_PIN: usize = 8;
pub static GATE_PIN: usize = 9;
pub static TRACK00_PIN: usize = 10;
pub static WRITE_PROTECT_PIN: usize = 11;
pub static READ_PIN: usize = 12; // This pin assigmnet is recrational. DO NOT CHANGE. It won't work.
pub static HEAD_SEL_PIN: usize = 14;
pub static DISK_CHANGE_PIN: usize = 15;
